### ISSUE TITLE
[Bug]: DatePicker & moment

### ISSUE THREAD

**Issue by FPT-NMTung** [FPT-NMTung/academic-management-system#34]
### What happened?

1. Vào trang chỉnh sửa SRO
2. bấm update

Thời gian, ngày tháng bị lùi 1 ngày.

### URL of website

http://localhost:3000/admin/account/sro/2/update

### Screenshots or Videos

https://user-images.githubusercontent.com/63092029/194676346-179ea0d9-4924-4f96-81ab-4363706b1878.mp4

### Expected behavior

Không bị thay đổi thời gian

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari, Microsoft Edge

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by nguyenht65** [comment]
xem cktg thôi bạn ơi code gì tầm này nữa =)))
