### ISSUE TITLE
[Bug]: Chưa hiển thị validator của create và update Course family

### ISSUE THREAD

**Issue by FPT-NMTung** [FPT-NMTung/academic-management-system#43]
### What happened?

1. Vào trang tạo course family
2. Nhập số năm là `2022aaaa`

Vẫn hiển thị 2022aaaa và phụ thuộc và bên backend trả về lỗi

### URL of website

https://ams.nmtung.dev/admin/manage-course/course-family

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/63092029/194918651-8fbf79cb-9f0c-4d18-ac84-28cb9369fb34.png)

### Expected behavior

Hiển thị validate ngay tại ô input để trực quan cho ng dùng

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari, Microsoft Edge

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by abcmonboi** [comment]
![image](https://user-images.githubusercontent.com/95062907/194992787-6544d64c-d9f1-4c5e-b73e-a97533a4992a.png)
