### ISSUE TITLE
[Bug]: Có thể add Trùng tên cơ sở ( bao gồm cả khác địa chỉ )

### ISSUE THREAD

**Issue by DUONGMON2000** [FPT-NMTung/academic-management-system#51]
### What happened?

1. Truy cập trang "Quản lý cơ sở" 
2. Click button "Thêm cơ sở"
3. Thêm một cơ sở với tên trùng với 1 cơ sở đã tồn tại
4.  Click button "Tạo mới"

### URL of website

https://ams.nmtung.dev/admin/center

### Expected behavior

Mỗi cơ sở chỉ có 1 tên tương ứng với 1 địa chỉ. Không thể thêm trùng.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by nguyenht65** [comment]
trùng tên (khác địa chỉ)
![image](https://user-images.githubusercontent.com/64007926/196591751-960b6591-0247-4f5f-9b92-448f71763922.png)

trùng tên (trùng địa chỉ)
![image](https://user-images.githubusercontent.com/64007926/196591854-63872d38-fa74-461c-91a0-a8d98375d34a.png)

khác tên nhưng địa chỉ đã tồn tại (dùng cho cơ sở khác)
![image](https://user-images.githubusercontent.com/64007926/196591918-84d1805d-cf19-460a-a040-964b8fe86d86.png)
