### ISSUE TITLE
[Bug]: Thay đổi tên cơ sở này trùng với cơ sở khác

### ISSUE THREAD

**Issue by DUONGMON2000** [FPT-NMTung/academic-management-system#52]
### What happened?

1. Truy cập trang "Quản lý cơ sở"
2. Click icon edit của một cơ sở bất kì
3. Đổi tên cơ sở đó trùng với 1 cơ sở đã tồn tại
4. Click button "Cập nhật"

### URL of website

https://ams.nmtung.dev/admin/center

### Expected behavior

Mỗi cơ sở chỉ có 1 tên với địa chỉ tương ứng, không thể trùng lặp

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by nguyenht65** [comment]
**tên cơ sở trùng tên cơ sở khác (khác địa chỉ)**
![image](https://user-images.githubusercontent.com/64007926/196596092-3a9d8439-6df4-4f8f-a1aa-9b7321ea60d2.png)
**tên cơ sở trùng tên cơ sở khác (cùng địa chỉ)**
![image](https://user-images.githubusercontent.com/64007926/196596193-8a84828f-8216-49c3-91d9-0646d3b729d6.png)
**Địa chỉ của cơ sở này khi thay đổi mà trùng với địa chỉ của cơ sở khác**
![image](https://user-images.githubusercontent.com/64007926/196596286-45411f32-c1ff-4ae9-a763-4181ae91dc42.png)
