### ISSUE TITLE
[Bug]: Không tạo được SRO mới

### ISSUE THREAD

**Issue by DUONGMON2000** [FPT-NMTung/academic-management-system#53]
### URL of website

https://ams.nmtung.dev/admin/account/sro/create

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/86470329/196436814-d8eba186-b3ae-4d99-a371-386afaf37d62.png)

### Expected behavior

Tạo SRO mới thành công

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by FPT-NMTung** [comment]
@thanhnm136 Check nhanh giúp t cái bug này nhé.
