### ISSUE TITLE
[Bug]: Mail cá nhân và mail tổ chức có thể trùng nhau

### ISSUE THREAD

**Issue by DUONGMON2000** [FPT-NMTung/academic-management-system#59]
### What happened?

1. Go to "Người quản lý lớp (SRO)" page
2. Click to view icon of a SRO
3. Click "Chỉnh sửa thông tin"
4. Edit personal email is the same as organizational email
5. Click button "Cập nhật"

### URL of website

https://ams.nmtung.dev/admin/account/sro/81

### Screenshots or Videos

![Uploading image.png…]()

### Expected behavior

Email cá nhân và email tổ chức phải khác nhau

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by FPT-NMTung** [comment]
lần build tới fix cái này luôn nhé @thanhnm136

**Comment by thanhnm136** [comment]
validate 2 cái email luôn đúng ko sếp @FPT-NMTung

**Comment by FPT-NMTung** [comment]
@thanhnm136 cứ check không cho 2 cái trùng là được nhé.
