### ISSUE TITLE
[Bug]: Trường Họ , tên đệm và Tên đang viết được số

### ISSUE THREAD

**Issue by DUONGMON2000** [FPT-NMTung/academic-management-system#74]
### What happened?

1. Access the "Tạo mới SRO" page.
2. Enter a name with numbers 

### URL of website

https://ams.nmtung.dev/admin/account/sro/create

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/86470329/197593462-18eb5d75-e6c7-418f-b420-50458c1cd1db.png)

### Expected behavior

Các trường thông tin liên quan tới Tên không được nhập số 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by FPT-NMTung** [comment]
@thanhnm136 thêm vào regex nhé, t thêm vào front-end trước.

**Comment by FPT-NMTung** [comment]
![image](https://user-images.githubusercontent.com/63092029/197598250-a40dd6f1-da72-43b0-99f8-c1f48564c2da.png)

Sẽ được deploy lên trong lần tới. dành cho cả 4 chức năng:
- Create SRO
- Update SRO
- Create Teacher
- Update Teacher

**Comment by thanhnm136** [comment]
Đã sửa, có gì test lại hộ mình nhé @DUONGMON2000
