### ISSUE TITLE
[Bug]: Màn hình bị đẩy đi khi thông tin quá dài

### ISSUE THREAD

**Issue by DUONGMON2000** [FPT-NMTung/academic-management-system#75]
### What happened?

1. Go to "Tài khoản SRO" page

### URL of website

https://ams.nmtung.dev/admin/account/sro

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/86470329/197596977-a9714c84-dba9-4c59-9f74-72f1886221a8.png)

### Expected behavior

Giới hạn độ dài hiển thị của các trường thông tin, để màn hình luôn hiển thị đủ thông tin ở mọi trường hợp.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by FPT-NMTung** [comment]
Quả này sửa cả cái web thì hơi ... khó 😥

**Comment by nguyenht65** [comment]
để cái thanh cuộn ngang ở dưới có được k nhỉ?

**Comment by FPT-NMTung** [comment]
> để cái thanh cuộn ngang ở dưới có được k nhỉ?

Để cuộn được phải có chiều dài cụ thể được đặt ra như 100px chẳng hạn. giờ web nhiều trường text quá, thêm hết chắc xỉu mất.
Còn cái table nó tự có cuộn rồi.
