### ISSUE TITLE
[Bug]: Chưa có nội dung message cho trước hợp nhập số lượng kí tự > max value

### ISSUE THREAD

**Issue by DUONGMON2000** [FPT-NMTung/academic-management-system#76]
### What happened?

1. Go to "Tạo mới SRO" page
2. Enter a name with >255 letters
3. Click button "Tạo mới"

### URL of website

https://ams.nmtung.dev/admin/account/sro/create

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/86470329/197598147-ee501f5d-413f-411c-a0fc-d16be8ef21b1.png)

### Expected behavior

Khi nhập quá giới hạn, phải xuất hiện message có nội dung lỗi

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by FPT-NMTung** [comment]
![image](https://user-images.githubusercontent.com/63092029/197599784-283ad9e1-3ade-4002-a51e-6afea3fd0503.png)

Thêm thông tin cảnh báo trước và không cho gửi form.

**Comment by FPT-NMTung** [comment]
@abcmonboi kiểm tra lại tất cả các màn hình của bạn (Admin) xem cái nào chưa có validate thì bổ sung.

**Comment by abcmonboi** [comment]
okay
